#!/bin/bash

set -xe

cd docker
docker build . -t cactus-rt-test
cd ..
docker run --rm \
  -e CACTUS_RT_ENABLE_TRACING=${CACTUS_RT_ENABLE_TRACING:-ON} \
  -it \
  --cap-add IPC_LOCK \
  -v $(pwd):/cactus-rt/source \
  cactus-rt-test
