on: [push]

name: cactus-rt

jobs:
  build-and-test:
    runs-on: [self-hosted, jammy]
    env:
      CACTUS_RT_BUILD_DIR: build
    steps:
      - uses: actions/checkout@v3

      - name: Check if clang format is necessary
        run: docker/scripts/00-format.sh

      - name: Setup dependencies
        run: sudo apt-get update && sudo apt-get install -y libspdlog-dev liblttng-ust-dev libboost-dev

      - name: Build library
        run: docker/scripts/01-build.sh

      - name: Test
        run: docker/scripts/02-test.sh
